# Generated by Django 2.1.2 on 2018-10-20 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('some_text', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=202)),
                ('groups', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('operator', models.CharField(max_length=200)),
                ('StatusExpire', models.DateTimeField(verbose_name='Дата просрочки')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата заключения контракта')),
                ('lastname2', models.CharField(max_length=200)),
                ('firstname2', models.CharField(max_length=200)),
                ('middlename2', models.CharField(max_length=200)),
                ('phone2', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
                ('product2', models.CharField(max_length=200)),
                ('PRIMARY', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.CharField(max_length=200)),
                ('some_integer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybank.Bid')),
            ],
        ),
    ]
