# Generated by Django 2.1.2 on 2018-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0002_remove_bid_some_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='PRIMARY',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='StatusExpire',
            field=models.DateTimeField(blank=True, verbose_name='Дата просрочки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='email2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='firstname2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='groups',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lastname2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='middlename2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bid',
            name='sex',
            field=models.CharField(choices=[('М', ' Male'), ('Ж', 'Female')], default='М', max_length=1),
        ),
    ]
