# Generated by Django 2.1.2 on 2018-10-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_auto_20181020_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='StatusExpire',
            field=models.DateTimeField(blank=True, default='', verbose_name='Дата просрочки'),
        ),
    ]
